name = "rekindle-stripe"
main = "worker.js"
compatibility_date = "2024-12-05"

[vars]
FIREBASE_PROJECT_ID = "rekindle-dd1fa"
# Secrets to be set via `wrangler secret put`:
# STRIPE_WEBHOOK_SECRET
# FIREBASE_CLIENT_EMAIL
# FIREBASE_PRIVATE_KEY
