# This file manages the "New Issue" page configuration

blank_issues_enabled: true
contact_links:
  - name: ğŸ Report a bug
    url: https://github.com/ReKindleOS/ReKindle/issues/new?template=bug_report.md
    about: Use this template to report a problem with the current code.
  - name: â“ Ask a question
    url: https://github.com/ReKindleOS/ReKindle/discussions/new?category=q-a
    about: Ask and answer questions about the project.
  - name: ğŸ’¡ Feature Request
    url: https://github.com/ReKindleOS/ReKindle/issues/new?template=feature_request.md
    about: Feature requests from users.
  - name: ğŸ›‘ Roadmap (Approved collaborators only)
    url: https://github.com/ReKindleOS/ReKindle/issues/new?template=feature_roadmap.md
    about: This link is for reference only. Feature ideas are reserved for collaborators.
